datasets:
  en:
    name: "fineweb_edu_en"
    score_normalization:
      enabled: false
    input_dir: "data/datasets/HuggingFaceFW/fineweb-edu"
    output_dir: "data/datasets/fineweb/en"
    buckets:
      - name: "2.5"
        min_score: 2.5
        max_score: 3.0
        sampling_rate: 0.25
      - name: "3.0"
        min_score: 3.0
        max_score: 3.5
        sampling_rate: 0.50
      - name: "3.5"
        min_score: 3.5
        max_score: 4.0
        sampling_rate: 0.80
      - name: "4.0"
        min_score: 4.0
        sampling_rate: 1.0
  zh:
    name: "fineweb_edu_zh"
    score_normalization:
      enabled: true
      multiplier: 5.0
    input_dir: "data/datasets/opencsg/Fineweb-Edu-Chinese-V2.1"
    output_dir: "data/datasets/fineweb/zh"
    buckets:
      - name: "2.5"
        min_score: 2.5
        max_score: 3.0
        sampling_rate: 0.40
      - name: "3.0"
        min_score: 3.0
        max_score: 3.5
        sampling_rate: 0.60
      - name: "3.5"
        min_score: 3.5
        max_score: 4.0
        sampling_rate: 0.90
      - name: "4.0"
        min_score: 4.0
        sampling_rate: 1.0
