workers: 30
tasks: 1000
random_seed: 42
compression: "zstd"
max_file_size_bytes: 536870912

logging:
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  level: "INFO"

trial:
  max_files: 5
  max_rows: 2000
  max_file_size_bytes: 134217728
