datasets:
  fineweb_en:
    name: "fineweb_edu_en"
    source: "data/datasets/fineweb/en"
    samples: 4000000
    buckets:
      4.0:
        count: 1800000
      3.5:
        count: 800000
      3.0:
        count: 800000
      2.5:
        count: 600000

  fineweb_zh:
    name: "fineweb_edu_zh"
    source: "data/datasets/fineweb/zh"
    samples: 4000000
    buckets:
      4.0:
        count: 1800000
      3.5:
        count: 800000
      3.0:
        count: 800000
      2.5:
        count: 600000

  github_code:
    name: "github_code"
    source: "data/datasets/nick007x/github-code-2025"
    samples: 5000000
    stars_filter:
      above-2-stars:
        count: 4200000
      below-2-stars:
        count: 800000

  nemotron_math:
    name: "nemotron_cc_math"
    source: "data/datasets/nvidia/Nemotron-CC-Math-v1"
    samples: 3000000
    buckets:
      4plus:
        count: 1500000
      4plus_MIND:
        count: 960000
      3:
        count: 540000

random_seed: 42
output_format: "parquet"
output_dir: "data/datasets/nanomind_tokenizer"
